### ISSUE TITLE
can't upload word list

### ISSUE THREAD

**Issue by ajem2019** [knoword/support#1]
I can't seem to upload my word list for some reason. I adhered to all the rules and it is in csv format but it still will not go up for some reason, some insight would really be appreciated.

**Comment by trevorblades** [comment]
Could you please upload or link to the list that you're trying to upload?
That will give me a better idea of what might be happening.

**Comment by ajem2019** [comment]
sure here's a link to download it. thanks

http://www.filedropper.com/words-i-forget

**Comment by ajem2019** [comment]
hey! I was wondering if you had a chance to check it out. (Side note: if you did I know I marked everything as an adjective I just didn't want to individually go through and mark each one respectively as a noun, verb etc)

**Comment by trevorblades** [comment]
I'm going to investigate this issue this weekend. I tried to download your word list and the link you provided didn't work. Could you try uploading it to Dropbox or Google Drive?

**Comment by ajem2019** [comment]
sure, here's a Dropbox link sorry about that.
https://www.dropbox.com/s/oz7cue86w4hb4wu/Words-I-forget%281%29.csv?dl=0

**Comment by trevorblades** [comment]
Thanks! I've taken a look at your CSV and managed to find the issue, and I'll give you some details about what I've found. I've also fixed your CSV and included a link at the bottom of this comment, so it will work for you next time you try to import it.

The first thing I found was that the file had a bunch of extra quotation marks in between the lines, which prevented the CSV from being interpreted properly. In addition, there were many lines that were being broken apart by commas. Since commas are used to separate columns in the CSV, you must quote any text that contains a comma in it.

For example, this line has a comma after "Lexicon", "person", "language", and "knowledge". To make this work properly with our format of `word,definition,part of speech`, the definition text must be quoted, since it contains commas.

```
Lexicon, the vocabulary of a person, language, or branch of knowledge,adjective
```

...becomes:

```
Lexicon,"the vocabulary of a person, language, or branch of knowledge",adjective
```

I noticed a few other instances where additional definitions appeared after the `part of speech` (last) column, which was also likely a point of confusion for our parser.

That being said, I've cleaned up your CSV file, and you can find it here: https://gist.github.com/trevorblades/2e229740645f9ea9ddfda7795699b90b

You should be able to view and download it, and then try importing the words again. I hope this helps! Please let me know if you're still experiencing issues with the reformatted file :)

Out of curiosity, what program did you use to generate the CSV?

**Comment by ajem2019** [comment]
ah that make sense, thanks for clearing that up and for going through and fixing everything. This definitely helps and I really appreciate it. Since I had written everything down on word pad I just used a basic rtf to csv converter:

 https://convertio.co/rtf-csv/

**Comment by ajem2019** [comment]
this is very strange, even with your editing of the list it still won't upload. here is a screenshot of the error  I receive 

https://www.dropbox.com/s/40jfojx7jkcrzh6/error.PNG?dl=0

**Comment by trevorblades** [comment]
@ajem2019 apologies for that! I've just made a change that should fix this issue. Could you try refreshing the page and trying one more time? 🙏

**Comment by ajem2019** [comment]
sure thing, I just tried but for or some reason I still get the same message, I downloaded the updated file from the same link. Do you think the problem could somehow be on my end? are you able to upload the it okay?

**Comment by trevorblades** [comment]
That was my bad. I made a fix to the code, but I forgot to mention that I also fixed a few additional issues in the CSV file. You can download the latest working version of the CSV here: https://gist.github.com/trevorblades/2e229740645f9ea9ddfda7795699b90b

I just confirmed that this version of the list is working, so you _should_ have no problem with it on your end!

![Screen Shot 2019-03-30 at 1 18 28 PM](https://user-images.githubusercontent.com/1216917/55281210-5e578980-52ee-11e9-96a3-a19e2724e6dd.png)

**Comment by ajem2019** [comment]
Great it worked! Thanks Trevor you're the man, again I appreciate all your help. I'm glad I can finally study these guys.

**Comment by trevorblades** [comment]
I'm glad it worked for you! If you wouldn't mind, I would be really interested to learn more about how you're using Knoword. Could you tell me how you heard of it, and what test(s) you're studying for?

**Comment by ajem2019** [comment]
sure! well I actually found it through google searching for word games to play. I'm also not really studying for anything in particular I'm just studying new words in general to help remember them and test my memory recall, hope this helps.
